# Generated by Django 5.0.2 on 2024-03-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registries',
            name='favored',
        ),
        migrations.AddField(
            model_name='registries',
            name='in_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registryitens',
            name='favored',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
