# Generated by Django 5.0.2 on 2024-03-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_registries_favored_registries_in_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registries',
            name='obs',
            field=models.TextField(blank=True, max_length=120),
        ),
    ]
