# Generated by Django 5.0.2 on 2024-03-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_registries_obs'),
    ]

    operations = [
        migrations.AddField(
            model_name='registryitens',
            name='marca',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
