# Generated by Django 5.0.2 on 2024-07-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monetary", "0002_transfers"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfers",
            name="value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
