# Generated by Django 5.0.2 on 2024-07-03 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monetary", "0004_transfers_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transfers",
            options={"ordering": ("date", "out_account", "in_account")},
        ),
    ]
